### ISSUE TITLE
 not enough arguments in call to cache.NewRedis

### ISSUE THREAD

**Issue by manhtd98** [CleverBamboo/go-shop-b2c#3]
I try to run your project:
```
cd $GOPATH/src
git clone
go mod tidy
go set -u -v
go build
```
and got this error
```
# go-shop-b2c/common/redis
common/redis/redis.go:17:31: not enough arguments in call to cache.NewRedis
	have (*cache.RedisOpts)
	want ("context".Context, *cache.RedisOpts)
```

**Comment by DevilWhale** [comment]
> I try to run your project:
> 
> ```
> cd $GOPATH/src
> git clone
> go mod tidy
> go set -u -v
> go build
> ```
> 
> and got this error
> 
> ```
> # go-shop-b2c/common/redis
> common/redis/redis.go:17:31: not enough arguments in call to cache.NewRedis
> 	have (*cache.RedisOpts)
> 	want ("context".Context, *cache.RedisOpts)
> ```

hello，How did you solve it？
